#!/bin/bash
#
# Extracts CDK stack outputs and generates the frontend .env.local file.
# Run this after 'cdk deploy' completes successfully.
#
# Usage:
#   ./setup-frontend.sh
#   ./setup-frontend.sh --region us-west-2
#   ./setup-frontend.sh --stack-name MyCustomStackName

set -euo pipefail

REGION="${AWS_DEFAULT_REGION:-us-east-1}"
STACK_NAME="CdkDataAnalystAssistantAgentcoreStrandsStack"
FRONTEND_DIR="amplify-data-analyst-conversational-assistant-agentcore-strands"

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --region) REGION="$2"; shift 2 ;;
    --stack-name) STACK_NAME="$2"; shift 2 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

echo "================================================"
echo "Data Analyst Conversational Assistant — Frontend Setup"
echo "================================================"
echo "Stack:  $STACK_NAME"
echo "Region: $REGION"
echo ""

# Fetch CDK outputs
echo "Fetching CDK stack outputs..."
get_output() {
  aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --region "$REGION" \
    --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" \
    --output text
}

AGENT_RUNTIME_ARN=$(get_output "AgentRuntimeArn")
QUESTION_ANSWERS_TABLE_NAME=$(get_output "QuestionAnswersTableName")
MEMORY_ID=$(get_output "MemoryId")

if [ -z "$AGENT_RUNTIME_ARN" ] || [ "$AGENT_RUNTIME_ARN" = "None" ]; then
  echo "ERROR: Could not find stack outputs. Is the CDK stack deployed?"
  echo "  Run: cd cdk-data-analyst-assistant-agentcore-strands && cdk deploy"
  exit 1
fi

echo ""
echo "Stack outputs:"
echo "  AgentRuntimeArn:          $AGENT_RUNTIME_ARN"
echo "  QuestionAnswersTableName: $QUESTION_ANSWERS_TABLE_NAME"
echo "  MemoryId:                 $MEMORY_ID"
echo ""

# Generate .env.local
ENV_FILE="$FRONTEND_DIR/.env.local"

cat > "$ENV_FILE" << EOF
# Auto-generated by setup-frontend.sh from CDK stack outputs
# Stack: $STACK_NAME | Region: $REGION

AGENT_RUNTIME_ARN=$AGENT_RUNTIME_ARN
QUESTION_ANSWERS_TABLE_NAME=$QUESTION_ANSWERS_TABLE_NAME
MEMORY_ID=$MEMORY_ID
AGENT_ENDPOINT_NAME=DEFAULT
MODEL_ID_FOR_CHART=us.anthropic.claude-haiku-4-5-20251001-v1:0
APP_NAME=Data Analyst Assistant
WELCOME_MESSAGE=I'm your AI Data Analyst Assistant. Ask me anything about the data — trends, rankings, comparisons, and more!
EOF

echo "Generated: $ENV_FILE"
echo ""

# Install frontend dependencies
echo "Installing frontend dependencies..."
cd "$FRONTEND_DIR"

if command -v pnpm &> /dev/null; then
  pnpm install
else
  echo "pnpm not found. Install it with: npm install -g pnpm"
  echo "Then run: cd $FRONTEND_DIR && pnpm install && pnpm ampx sandbox"
  exit 0
fi

echo ""
echo "================================================"
echo "Frontend setup complete!"
echo "================================================"
echo ""
echo "Next steps:"
echo "  cd $FRONTEND_DIR"
echo "  pnpm ampx sandbox    # Deploy Cognito + IAM"
echo "  pnpm dev             # Start dev server at http://localhost:3000"
echo ""